/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/composition': RouteRecordInfo<'/composition', '/composition', Record<never, never>, Record<never, never>>,
    '/default-mode': RouteRecordInfo<'/default-mode', '/default-mode', Record<never, never>, Record<never, never>>,
    '/defer': RouteRecordInfo<'/defer', '/defer', Record<never, never>, Record<never, never>>,
    '/instance-type': RouteRecordInfo<'/instance-type', '/instance-type', Record<never, never>, Record<never, never>>,
    '/life-update': RouteRecordInfo<'/life-update', '/life-update', Record<never, never>, Record<never, never>>,
    '/reactive': RouteRecordInfo<'/reactive', '/reactive', Record<never, never>, Record<never, never>>,
    '/scoped-deep/': RouteRecordInfo<'/scoped-deep/', '/scoped-deep', Record<never, never>, Record<never, never>>,
    '/scoped-deep/components/Child': RouteRecordInfo<'/scoped-deep/components/Child', '/scoped-deep/components/Child', Record<never, never>, Record<never, never>>,
    '/vapor-mode.vapor': RouteRecordInfo<'/vapor-mode.vapor', '/vapor-mode/vapor', Record<never, never>, Record<never, never>>,
  }
}
